### ISSUE TITLE
Support older decode versions automatically (ex from height 0 -> 2.5m)

### ISSUE THREAD

**Issue by Reecepbcups** [Reecepbcups/juno-decode#1]
thread:1 Total Txs in Blocks: 780000->785000: 1175
panic: invalid character 'B' after top-level value

goroutine 1 [running]:
main.check(...)
        /root/juno-decoder/main.go:105
main.GetFileDecodeCommand.func1(0xc000c85500?, {0xc001167ea0, 0x2, 0x2?})
        /root/juno-decoder/main.go:137 +0x405
        /root/juno-decoder/main.go:137 +0x405
github.com/spf13/cobra.(*Command).execute(0xc0001a7500, {0xc000ffce00, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001a6c00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc000fc0450, 0xb})
        /root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.14/server/cmd/execute.go:36 +0x1eb
main.main()
        /root/juno-decoder/main.go:27 +0x2c
thread:2 Time: Decoded & stored (2091 Txs): 0.31848645210266113

If error in a decode, just return an empty string for the JSON. THis way when its updated in the SQL it can still be run again.
Then also save to a file for the block / Transaction which is the issue

**Comment by Reecepbcups** [comment]
nvm may just have been due to not using random for the JSON text file values
